name: Automated Test

on: [push]

jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Produce results1.txt output
        run: python3 find_lowest_number.py test_data/test1_input.txt output.txt

      - name: Compare expected output to actual
        run: diff test_data/test1_expected.txt output.txt
      
      - name: Produce results2.txt output
        run: python3 find_lowest_number.py test_data/test2_input.txt output2.txt

      - name: Compare expected output to actual
        run: diff test_data/test2_expected.txt output2.txt

      - name: Produce results3.txt output
        run: python3 find_lowest_number.py test_data/test3_input.txt output3.txt

      - name: Compare expected output to actual
        run: diff test_data/test3_expected.txt output3.txt
